### ISSUE TITLE
Bug: Can't remove items from 3D viewer

### ISSUE THREAD

**Issue by tomlawesome** [EduardoOliveira/stLib#2]
### Bug:
Can't remove models that are loaded into 3D viewer

### Description:
When more than one model is selected for 3D viewing they are in the viewer at the same time.

### Steps to repeat:
Select 3D view on a model.
Select 3D view on another. 
There is now no way to remove first/second item from view without refreshing the page.

**Comment by EduardoOliveira** [comment]
The intended functionality is to allow the user to add multiple models to the viewer.
This makes sense, for instance, in some miniature models that are comprised of multiple parts/interchangeable parts.

I've turned the add to viewer button into a toggle, that allows you to remove that model if you want.

That should be pushed later today or tomorrow.

**Comment by EduardoOliveira** [comment]
Implemented on v0.6
